name: Go

on: [push, pull_request]

env:
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy
  kind-version: v0.27.0
  go-version: 1.25

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check license
      run: make check-license

  generate:
    name: Generate
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Golang Environment
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ env.go-version }}

    - name: Generate
      run: make generate && git diff --exit-code

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Lint Go
      uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
      with:
        version: latest

  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Golang Environment
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: make build

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Golang Environment
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ env.go-version }}

    - name: Run unit tests
      run: make test-unit

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Golang Environment
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ env.go-version }}

    - name: Start kind & create cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        version: ${{ env.kind-version }}
        config: test/e2e/kind-config/kind-config.yaml
        cluster_name: kind
        wait: 300s

    - name: Wait for cluster to finish bootstraping
      run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

    - name: Create container & run tests
      run: |
        VERSION=local VERSION_SEMVER=$(cat ./VERSION) make container
        kind load docker-image ${QUAY_PATH}:local
        until docker exec $(kind get nodes) crictl images | grep "${QUAY_PATH}"; do
          echo "no kube-rbac-proxy image"
          sleep 1
        done
        make test-e2e

  publish:
    name: Publish container image to Quay
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: ${{ github.event.repository.fork == false && github.event_name == 'push' }}
    needs:
    - check-license
    - generate
    - build
    - unit-tests
    - e2e-tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Golang Environment
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ env.go-version }}

    - name: Login to Quay.io
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build images and push
      run: ./scripts/publish.sh
