name: Go

on: [push, pull_request]

env:
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy
  kind-version: v0.30.0
  go-version: 1.25.5

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Check license
      run: make check-license

  generate:
    name: Generate
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Setup Golang Environment
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.go-version }}

    - name: Generate
      run: make generate && git diff --exit-code

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Lint Go
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: latest

  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Setup Golang Environment
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: make build

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Setup Golang Environment
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.go-version }}

    - name: Run unit tests
      run: make test-unit

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Setup Golang Environment
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.go-version }}

    - name: Start kind & create cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        version: ${{ env.kind-version }}
        config: test/e2e/kind-config/kind-config.yaml
        cluster_name: kind
        wait: 300s

    - name: Wait for cluster to finish bootstraping
      run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

    - name: Create container & run tests
      run: |
        VERSION=local VERSION_SEMVER=$(cat ./VERSION) make container
        kind load docker-image ${QUAY_PATH}:local
        until docker exec $(kind get nodes) crictl images | grep "${QUAY_PATH}"; do
          echo "no kube-rbac-proxy image"
          sleep 1
        done
        make test-e2e

