name: Go

on: [push, pull_request]

env:
  VERSION: 1.13.x
  GO111MODULE: on
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy
  QUAY_REPOSITORY: quay.io/markku/kube-rbac-proxy
  kind-version: 'v0.7.0'
  kind-image: 'kind-linux-amd64'

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Start kind & create cluster
      uses: engineerd/setup-kind@v0.4.0
      with:
        version: ${{ env.kind-version }}
        # image: ${{ env.kind-image }}
    - name: Wait for cluster to finish bootstraping
      # run: |
      #   until [ "$(kubectl get pods --all-namespaces --no-headers | grep -cEv '([0-9]+)/\1')" -eq 0 ]; do
      #       sleep 5s
      #   done
      #   kubectl cluster-info
      #   kubectl get pods -A
      # run: |
      #   curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
      #   kind create cluster --config test/e2e/kind-config/kind-config.yaml
      continue-on-error: false
    - name: Create container & run tests
      run: |
        VERSION=local make container
        kind load docker-image ${QUAY_PATH}:local
        make test-e2e
    - name: Login and push to Quay
      if: github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
      run: |
        TAG="$(git rev-parse --abbrev-ref HEAD | tr / -)-$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)"
        ID="$(docker images ${QUAY_PATH}:local --format "{{.ID}}")"
        docker tag $ID ${QUAY_REPOSITORY}:$TAG
        docker push ${QUAY_REPOSITORY}:$TAG
